// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrYS2hi2JeRU9CxUJUE-2pZWlbDSKUAHI',
    appId: '1:622495011859:web:f8e6ba332d8831c319dbe6',
    messagingSenderId: '622495011859',
    projectId: 'kiwo-e0aae',
    authDomain: 'kiwo-e0aae.firebaseapp.com',
    storageBucket: 'kiwo-e0aae.firebasestorage.app',
    measurementId: 'G-YR79ZRBCG8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzHr9gEsJGsfm_q0dJW1MKDzZiCwhT8GU',
    appId: '1:622495011859:android:a50aec6ef7cb4a9019dbe6',
    messagingSenderId: '622495011859',
    projectId: 'kiwo-e0aae',
    storageBucket: 'kiwo-e0aae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD65_I2c_n7x-PW7x2-q2a0_m0h8YW6xJ4',
    appId: '1:622495011859:ios:1e3e731f11be36ed19dbe6',
    messagingSenderId: '622495011859',
    projectId: 'kiwo-e0aae',
    storageBucket: 'kiwo-e0aae.firebasestorage.app',
    iosBundleId: 'com.example.kiwo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD65_I2c_n7x-PW7x2-q2a0_m0h8YW6xJ4',
    appId: '1:622495011859:ios:1e3e731f11be36ed19dbe6',
    messagingSenderId: '622495011859',
    projectId: 'kiwo-e0aae',
    storageBucket: 'kiwo-e0aae.firebasestorage.app',
    iosBundleId: 'com.example.kiwo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrYS2hi2JeRU9CxUJUE-2pZWlbDSKUAHI',
    appId: '1:622495011859:web:77aca064cf598eb819dbe6',
    messagingSenderId: '622495011859',
    projectId: 'kiwo-e0aae',
    authDomain: 'kiwo-e0aae.firebaseapp.com',
    storageBucket: 'kiwo-e0aae.firebasestorage.app',
    measurementId: 'G-PH43R8CJ4P',
  );
}
